name: ChunkLoader
version: '${project.version}'
main: dev.mrjb.chunkloader.chunkloader.ChunkLoader
api-version: '1.20'
description: A plugin to force load and unload chunks.
commands:
  chunk:
    description: Load or unload chunks.
    usage: /chunk <load|unload>
  hello:
    description: For test.
